{% set name = "pymatgen-lammps" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymatgen-lammps-{{ version }}.tar.gz
  sha256: 42b455b73ebbdd5babe9194e528bd5ad5768f498a537d0d69f40315f2930fed4
  patches:
    - pymatgen.patch

build:
  number: 1
  noarch: python
  entry_points:
    - pylammps=pmg_lammps.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools >=38.6.0
  run:
    - pymatgen
    - python >={{ python_min }}
    - pyzmq

test:
  imports:
    - pmg_lammps
    - pmg_lammps.calculator
  commands:
    - pip check
    - pylammps --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home:  https://github.com/costrouc/pymatgen-lammps
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Lammps Wrapper'
  description: |
    This is a package that I wrote to write input files for LAMMPS
    and analyze them because I was not happy with the one built
    inside of pymatgen. It has built in calculators for running
    many lammps calculations in parallel (many short small LAMMPS
    calculations).
  doc_url: https://github.com/costrouc/pymatgen-lammps
  dev_url: https://github.com/costrouc/pymatgen-lammps

extra:
  recipe-maintainers:
    - jan-janssen
